apiVersion: v1
kind: Service
metadata:
  labels:
    app: openclaw
  name: openclaw
  namespace: openclaw
spec:
  type: LoadBalancer
  ports:
  - name: gateway
    port: 18789
    protocol: TCP
    targetPort: 18789
  - name: bridge
    port: 18790
    protocol: TCP
    targetPort: 18790
  selector:
    app: openclaw
